version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: svelte-lunch
      POSTGRES_USER: kaleb
      POSTGRES_PASSWORD: kaleb@1234
    ports:
      - "5432:5432"
